export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAIL = "DELETE_FAIL";

//USER REGISTRATION
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

//USER LOGIN
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

//USER LOGOUT
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

//USER PROFILE
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

// FETCH USERS
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

//LOADING
export const LOADING_TRUE = "LOADING_TRUE";
export const LOADING_FALSE = "LOADING_FALSE";

export const CREATE_REQUEST = "CREATE_REQUEST";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAIL = "CREATE_FAIL";

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";

export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";

export const GET_OFFRE_SUCCESS = "GET_OFFRE_SUCCESS";
export const CREATE_OFFRE_SUCCESS = "CREATE_OFFRE_SUCCESS";
export const DELETE_OFFRE_SUCCESS = "DELETE_OFFRE_SUCCESS";
export const DELETE_OFFRE_FAIL = "DELETE_OFFRE_FAIL";
export const OFFRE_ERROR = "OFFRE_ERROR";

//stock
export const GET_STOCK_REQ = "GET_STOCK_REQ";
export const GET_STOCK_FAIL = "GET_STOCK_FAIL";
export const GET_STOCK_SUCCESS = "GET_STOCK_SUCCESS";
export const GET_STOCK = "GET_STOCK";
export const STOCK_ERROR = "STOCK_ERROR";
export const CREATE_STOCK_REQ = "CREATE_STOCK_REQ";
export const CREATE_STOCK_SUCCESS = "CREATE_STOCK_SUCCESS";
export const CREATE_STOCK_FAIL = "CREATE_STOCK_FAIL";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";
export const DELETE_STOCK_FAIL = "DELETE_STOCK_FAIL";

//caisse
export const GET_CAISSE_SUCCESS = "GET_CAISSE_SUCCESS";
export const CREATE_CAISSE_SUCCESS = "CREATE_CAISSE_SUCCESS";
export const DELETE_CAISSE_SUCCESS = "DELETE_CAISSE_SUCCESS";
export const GET_CAISSE = "GET_CAISSE";
export const CAISSE_ERROR = "CAISSE_ERROR";

//finance
export const GET_FINANCE_SUCCESS = "GET_FINANCE_SUCCESS";
export const FINANCE_ERROR = "FINANCE_ERROR";
export const GET_FINANCE = "GET_FINANCE";
export const CREATE_FINANCE_SUCCESS = "CREATE_FINANCE_SUCCESS";
export const DELETE_FINANCE_SUCCESS = "DELETE_FINANCE_SUCCESS";

//document
export const GET_DOC_SUCCESS = "GET_DOC_SUCCESS";
export const DOCUMENT_ERROR = "DOCUMENT_ERROR";
export const CREATE_DOC_SUCCESS = "CREATE_DOC_SUCCESS";
export const DELETE_DOC_SUCCESS = "DELETE_DOC_SUCCESS";

//rapport du medecin
export const GET_RAPPORT_MEDECIN = "GET_RAPPORT_MEDECIN";
export const RAPPORT_MEDECIN_ERROR = "RAPPORT_MEDECIN_ERROR";
export const CREATE_RAPPORT_MEDECIN_SUCCESS = "CREATE_RAPPORT_MEDECIN_SUCCESS";
export const DELETE_RAPPORT_MEDECIN_SUCCESS = "DELETE_RAPPORT_MEDECIN_SUCCESS";

//patient
export const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";
export const CREATE_PATIENT_SUCCESS = "CREATE_PATIENT_SUCCESS";
export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";
export const PATIENT_ERROR = "PATIENT_ERROR";

export const GET_DOSSMED_SUCCESS = "GET_DOSSMED_SUCCESS";
export const DOSSMED_ERROR = "DOSSMED_ERROR";
export const CREATE_DOSSMED_SUCCESS = "CREATE_DOSSMED_SUCCESS";
export const DELETE_DOSSMED_SUCCESS = "DELETE_DOSSMED_SUCCESS";

export const GET_AHOSP_SUCCESS = "GET_AHOSP_SUCCESS";
export const CREATE_AHOSP_SUCCESS = "CREATE_AHOSP_SUCCESS";
export const DELETE_AHOSP_SUCCESS = "DELETE_AHOSP_SUCCESS";
export const AVISHOS_ERROR = "AVISHOS_ERROR";

export const GET_BULSORT_SUCCESS = "GET_BULSORT_SUCCESS";
export const CREATE_BULSORT_SUCCESS = "CREATE_BULSORT_SUCCESS";
export const DELETE_BULSORT_SUCCESS = "DELETE_BULSORT_SUCCESS";
export const BULSORT_ERROR = "BULSORT_ERROR";

export const GET_BE_SUCCESS = "GET_BE_SUCCESS";
export const BE_ERROR = "BE_ERROR";
export const CREATE_BE_SUCCESS = "CREATE_BE_SUCCESS";
export const UPDATE_BE_SUCCESS = "UPDATE_BE_SUCCESS";
export const DELETE_BE_SUCCESS = "DELETE_BE_SUCCESS";

export const GET_CA_SUCCESS = "GET_CA_SUCCESS";
export const CA_ERROR = "CA_ERROR";
export const CREATE_CA_SUCCESS = "CREATE_CA_SUCCESS";
export const UPDATE_CA_SUCCESS = "UPDATE_CA_SUCCESS";
export const DELETE_CA_SUCCESS = "DELETE_CA_SUCCESS";

export const GET_CG_SUCCESS = "GET_CG_SUCCESS";
export const CG_ERROR = "CG_ERROR";
export const CREATE_CG_SUCCESS = "CREATE_CG_SUCCESS";
export const UPDATE_CG_SUCCESS = "UPDATE_CG_SUCCESS";
export const DELETE_CG_SUCCESS = "DELETE_CG_SUCCESS";

export const GET_CMED_SUCCESS = "GET_CMED_SUCCESS";
export const CMED_ERROR = "CMED_ERROR";
export const CREATE_CMED_SUCCESS = "CREATE_CMED_SUCCESS";
export const UPDATE_CMED_SUCCESS = "UPDATE_CMED_SUCCESS";
export const DELETE_CMED_SUCCESS = "DELETE_CMED_SUCCESS";

export const GET_CVM_SUCCESS = "GET_CVM_SUCCESS";
export const CVM_ERROR = "CVM_ERROR";
export const CREATE_CVM_SUCCESS = "CREATE_CVM_SUCCESS";
export const UPDATE_CVM_SUCCESS = "UPDATE_CVM_SUCCESS";
export const DELETE_CVM_SUCCESS = "DELETE_CVM_SUCCESS";

export const GET_CVCVM_SUCCESS = "GET_CVCVM_SUCCESS";
export const CVCVM_ERROR = "CVCVM_ERROR";
export const CREATE_CVCVM_SUCCESS = "CREATE_CVCVM_SUCCESS";
export const UPDATE_CVCVM_SUCCESS = "UPDATE_CVCVM_SUCCESS";
export const DELETE_CVCVM_SUCCESS = "DELETE_CVCVM_SUCCESS";

export const GET_COMPACC_SUCCESS = "GET_COMPACC_SUCCESS";
export const COMPACC_ERROR = "COMPACC_ERROR";
export const CREATE_COMPACC_SUCCESS = "CREATE_COMPACC_SUCCESS";
export const UPDATE_COMPACC_SUCCESS = "UPDATE_COMPACC_SUCCESS";
export const DELETE_COMPACC_SUCCESS = "DELETE_COMPACC_SUCCESS";

export const GET_COMPHOSP_SUCCESS = "GET_COMPHOSP_SUCCESS";
export const COMPHOSP_ERROR = "COMPHOSP_ERROR";
export const CREATE_COMPHOSP_SUCCESS = "CREATE_COMPHOSP_SUCCESS";
export const UPDATE_COMPHOSP_SUCCESS = "UPDATE_COMPHOSP_SUCCESS";
export const DELETE_COMPHOSP_SUCCESS = "DELETE_COMPHOSP_SUCCESS";

export const GET_CONGE_SUCCESS = "GET_CONGE_SUCCESS";
export const CONGE_ERROR = "CONGE_ERROR";
export const CREATE_CONGE_SUCCESS = "CREATE_CONGE_SUCCESS";
export const UPDATE_CONGE_SUCCESS = "UPDATE_CONGE_SUCCESS";
export const DELETE_CONGE_SUCCESS = "DELETE_CONGE_SUCCESS";

export const GET_CONPE_SUCCESS = "GET_CONPE_SUCCESS";
export const CONPE_ERROR = "CONPE_ERROR";
export const CREATE_CONPE_SUCCESS = "CREATE_CONPE_SUCCESS";
export const UPDATE_CONPE_SUCCESS = "UPDATE_CONPE_SUCCESS";
export const DELETE_CONPE_SUCCESS = "DELETE_CONPE_SUCCESS";

export const GET_CONIM_SUCCESS = "GET_CONIM_SUCCESS";
export const CONIM_ERROR = "CONIM_ERROR";
export const CREATE_CONIM_SUCCESS = "CREATE_CONIM_SUCCESS";
export const UPDATE_CONIM_SUCCESS = "UPDATE_CONIM_SUCCESS";
export const DELETE_CONIM_SUCCESS = "DELETE_CONIM_SUCCESS";

export const GET_DECHARGE_SUCCESS = "GET_DECHARGE_SUCCESS";
export const DECHARGE_ERROR = "DECHARGE_ERROR";
export const CREATE_DECHARGE_SUCCESS = "CREATE_DECHARGE_SUCCESS";
export const UPDATE_DECHARGE_SUCCESS = "UPDATE_DECHARGE_SUCCESS";
export const DELETE_DECHARGE_SUCCESS = "DELETE_DECHARGE_SUCCESS";

export const GET_ECHOABD_SUCCESS = "GET_ECHOABD_SUCCESS";
export const ECHOABD_ERROR = "ECHOABD_ERROR";
export const CREATE_ECHOABD_SUCCESS = "CREATE_ECHOABD_SUCCESS";
export const UPDATE_ECHOABD_SUCCESS = "UPDATE_ECHOABD_SUCCESS";
export const DELETE_ECHOABD_SUCCESS = "DELETE_ECHOABD_SUCCESS";

export const GET_ECHOPROS_SUCCESS = "GET_ECHOPROS_SUCCESS";
export const ECHOPROS_ERROR = "ECHOPROS_ERROR";
export const CREATE_ECHOPROS_SUCCESS = "CREATE_ECHOPROS_SUCCESS";
export const UPDATE_ECHOPROS_SUCCESS = "UPDATE_ECHOPROS_SUCCESS";
export const DELETE_ECHOPROS_SUCCESS = "DELETE_ECHOPROS_SUCCESS";

export const GET_FT_SUCCESS = "GET_FT_SUCCESS";
export const FT_ERROR = "FT_ERROR";
export const CREATE_FT_SUCCESS = "CREATE_FT_SUCCESS";
export const UPDATE_FT_SUCCESS = "UPDATE_FT_SUCCESS";
export const DELETE_FT_SUCCESS = "DELETE_FT_SUCCESS";

export const GET_ORD_SUCCESS = "GET_ORD_SUCCESS";
export const ORD_ERROR = "ORD_ERROR";
export const CREATE_ORD_SUCCESS = "CREATE_ORD_SUCCESS";
export const UPDATE_ORD_SUCCESS = "UPDATE_ORD_SUCCESS";
export const DELETE_ORD_SUCCESS = "DELETE_ORD_SUCCESS";

export const GET_SU_SUCCESS = "GET_SU_SUCCESS";
export const SU_ERROR = "SU_ERROR";
export const CREATE_SU_SUCCESS = "CREATE_SU_SUCCESS";
export const UPDATE_SU_SUCCESS = "UPDATE_SU_SUCCESS";
export const DELETE_SU_SUCCESS = "DELETE_SU_SUCCESS";

export const GET_ACCUEIL_SUCCESS = "GET_ACCUEIL_SUCCESS";
export const ACCUEIL_ERROR = "ACCUEIL_ERROR";
export const CREATE_ACCUEIL_SUCCESS = "CREATE_ACCUEIL_SUCCESS";
export const UPDATE_ACCUEIL_SUCCESS = "UPDATE_ACCUEIL_SUCCESS";
export const DELETE_ACCUEIL_SUCCESS = "DELETE_ACCUEIL_SUCCESS";

export const GET_MEDECIN_SUCCESS = "GET_MEDECIN_SUCCESS";
export const MEDECIN_ERROR = "MEDECIN_ERROR";
export const CREATE_MEDECIN_SUCCESS = "CREATE_MEDECIN_SUCCESS";
export const UPDATE_MEDECIN_SUCCESS = "UPDATE_MEDECIN_SUCCESS";
export const DELETE_MEDECIN_SUCCESS = "DELETE_MEDECIN_SUCCESS";

export const RETIRER_SUCCESS = "RETIRER_SUCCESS";
export const RETIRER_ERROR = "RETIRER_ERROR";

export const VALIDATION_SUCCESS = "VALIDATION_SUCCESS";
export const VALIDATION_ERROR = "VALIDATION_ERROR";

export const GET_ONE_SUCCESS = "GET_ONE_SUCCESS";
export const GET_SUCCESS = "GET_SUCCESS";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
