import React, { Component } from "react";
import { Entete1 } from "../../layout/Entetes";
import "./style.css";

class PrintFicheTemperature extends Component {
  render() {
    const { date, namePatient, lastNamePatient, dateDeNaissance, data } =
      this.props;
    return (
      <div className='A4 ficheTe ficheT' style={{ fontSize: "11px" }}>
        <Entete1 date={date} />
        <div className='text-capitalize my-4'>
          <div className='row'>
            <div className='col-5'>
              Nom et Prénom:{" "}
              <span className='fw-bolder'>
                {namePatient} {lastNamePatient}{" "}
              </span>
            </div>
            <div className='col-3 text-center'>
              age:{" "}
              <span className='fw-bolder'>
                {parseInt(date.getFullYear()) - parseInt(dateDeNaissance)}
                {parseInt(date.getFullYear()) - parseInt(dateDeNaissance) > 1
                  ? "ans"
                  : "an"}
              </span>
            </div>
            <div className='col-4 text-end'>
              Sexe: <span className='fw-bolder'>{data.sexe}</span>
            </div>
          </div>
          <div className='row'>
            <div className='col-6'>
              Poids: <span className='fw-bolder'>{data.poids} Kg</span>
            </div>
            <div className='col-6 text-end'>
              Chambre N° : <span className='fw-bolder'>{data.chambre}</span>
            </div>
          </div>
        </div>
        <div className='table-responsive mt-4'>
          <table id='table' className='p-auto text-center'>
            <thead>
              <tr>
                <th style={{ width: 250 }}>TRAITEMENT</th>
                <th className='text-center'>
                  J1
                  <tr>
                    <td>M</td>
                    <td>M</td>
                    <td>S</td>
                  </tr>
                </th>
                <th className='text-center'>
                  J2
                  <tr>
                    <td>M</td>
                    <td>M</td>
                    <td>S</td>
                  </tr>
                </th>
                <th className='text-center'>
                  J3
                  <tr>
                    <td>M</td>
                    <td>M</td>
                    <td>S</td>
                  </tr>
                </th>
                <th className='text-center'>
                  J4
                  <tr>
                    <td>M</td>
                    <td>M</td>
                    <td>S</td>
                  </tr>
                </th>
                <th className='text-center'>
                  J5
                  <tr>
                    <td>M</td>
                    <td>M</td>
                    <td>S</td>
                  </tr>
                </th>
                <th className='text-center'>
                  J6
                  <tr>
                    <td>M</td>
                    <td>M</td>
                    <td>S</td>
                  </tr>
                </th>
              </tr>
            </thead>
            <tbody>
              {data.traitement.map((el, index) => {
                //console.log(el, index);
                return (
                  <tr key={index}>
                    <td>{el.labbel}</td>
                    <td>
                      <tr>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j1matin}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j1midi}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j1soir}
                          />
                        </td>
                      </tr>
                    </td>
                    <td>
                      <tr>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j2matin}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j2midi}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j2soir}
                          />
                        </td>
                      </tr>
                    </td>
                    <td>
                      <tr>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j3matin}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j3midi}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j3soir}
                          />
                        </td>
                      </tr>
                    </td>
                    <td>
                      <tr>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j4matin}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j4midi}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j4soir}
                          />
                        </td>
                      </tr>
                    </td>
                    <td>
                      <tr>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j5matin}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j5midi}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j5soir}
                          />
                        </td>
                      </tr>
                    </td>
                    <td>
                      <tr>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j6matin}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j6midi}
                          />
                        </td>
                        <td>
                          <input
                            type='checkbox'
                            readOnly
                            defaultChecked={el.j6soir}
                          />
                        </td>
                      </tr>
                    </td>
                  </tr>
                );
              })}

              <tr className='bg-secondary text-center text-light'>
                <th>
                  <td>FR</td>
                  <td>Ur cc</td>
                  <td>Pouls</td>
                  <td>TA</td>
                  <td>T°</td>
                </th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
              <tr>
                <td>
                  <td></td>
                  <td>3500</td>
                  <td>180</td>
                  <td></td>
                  <td>42°</td>
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t42.j1}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t42.j2}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t42.j3}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t42.j4}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t42.j5}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t42.j6}
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <td></td>
                  <td>3000</td>
                  <td>160</td>
                  <td></td>
                  <td>41°</td>
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t41.j1}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t41.j2}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t41.j3}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t41.j4}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t41.j5}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t41.j6}
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <td>50</td>
                  <td>2500</td>
                  <td>140</td>
                  <td>25</td>
                  <td>40°</td>
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t40.j1}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t40.j2}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t40.j3}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t40.j4}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t40.j5}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t40.j6}
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <td>40</td>
                  <td>2000</td>
                  <td>120</td>
                  <td>20</td>
                  <td>39°</td>
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t39.j1}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t39.j2}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t39.j3}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t39.j4}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t39.j5}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t39.j6}
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <td>30</td>
                  <td>1500</td>
                  <td>100</td>
                  <td>15</td>
                  <td>38°</td>
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t38.j1}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t38.j2}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t38.j3}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t38.j4}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t38.j5}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t38.j6}
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <td>20</td>
                  <td>1000</td>
                  <td>80</td>
                  <td>10</td>
                  <td>37°</td>
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t37.j1}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t37.j2}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t37.j3}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t37.j4}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t37.j5}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t37.j6}
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <td>10</td>
                  <td>500</td>
                  <td>60</td>
                  <td>5</td>
                  <td>36°</td>
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t36.j1}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t36.j2}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t36.j3}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t36.j4}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t36.j5}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t36.j6}
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <td></td>
                  <td>0</td>
                  <td>40</td>
                  <td></td>
                  <td>35°</td>
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t35.j1}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t35.j2}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t35.j3}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t35.j4}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t35.j5}
                  />
                </td>
                <td>
                  <input
                    type='checkbox'
                    readOnly
                    defaultChecked={data?.t35.j6}
                  />
                </td>
              </tr>
            </tbody>
            <tfoot>
              <tr>
                <th rowSpan={6}>EXAMENS COMPLEMENTAIRES</th>
                <th colSpan={6}>
                  {data.examensComplementaires.map((it, index) => (
                    <tr className='border-0' key={index}>
                      {it}{" "}
                    </tr>
                  ))}
                </th>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    );
  }
}

export default PrintFicheTemperature;
